/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stanibogat1;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import stanibogat1.Register;
import stanibogat1.FileWorker;
import stanibogat1.StartGamePanel;
import stanibogat1.StartGamePanel;
import stanibogat1.User;
import stanibogat1.User;



/**
 *
 * @author mac
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public Login() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("LOG IN");
        notlbl.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpnl = new javax.swing.JPanel();
        lblUSERNAME = new javax.swing.JLabel();
        lblPASSWORD = new javax.swing.JLabel();
        txtfldUSERNAME = new javax.swing.JTextField();
        btnLOGIN = new javax.swing.JButton();
        btnREGISTER = new javax.swing.JButton();
        notlbl = new javax.swing.JLabel();
        pswrdfldlogin = new javax.swing.JPasswordField();
        loginpnl = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblWELCOME1 = new javax.swing.JLabel();
        lblMinimise = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        mainpnl.setBackground(new java.awt.Color(51, 51, 255));

        lblUSERNAME.setFont(new java.awt.Font("Apple Braille", 2, 18)); // NOI18N
        lblUSERNAME.setForeground(new java.awt.Color(255, 255, 255));
        lblUSERNAME.setText("Потребителско име :");

        lblPASSWORD.setFont(new java.awt.Font("Apple Braille", 2, 18)); // NOI18N
        lblPASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        lblPASSWORD.setText("Парола :");

        txtfldUSERNAME.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        btnLOGIN.setBackground(new java.awt.Color(0, 153, 255));
        btnLOGIN.setFont(new java.awt.Font("Al Nile", 1, 14)); // NOI18N
        btnLOGIN.setForeground(new java.awt.Color(255, 255, 255));
        btnLOGIN.setText("Вход");
        btnLOGIN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGINActionPerformed(evt);
            }
        });

        btnREGISTER.setBackground(new java.awt.Color(204, 0, 0));
        btnREGISTER.setFont(new java.awt.Font("Al Nile", 1, 14)); // NOI18N
        btnREGISTER.setForeground(new java.awt.Color(255, 255, 255));
        btnREGISTER.setText("Регистрация");
        btnREGISTER.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnREGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREGISTERActionPerformed(evt);
            }
        });

        notlbl.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        notlbl.setForeground(new java.awt.Color(255, 255, 255));
        notlbl.setText("Акаунтът не съществува");

        pswrdfldlogin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        loginpnl.setBackground(new java.awt.Color(102, 102, 255));

        lblClose.setFont(new java.awt.Font("Apple Braille", 2, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("x");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblWELCOME1.setFont(new java.awt.Font("Apple Braille", 2, 24)); // NOI18N
        lblWELCOME1.setForeground(new java.awt.Color(255, 255, 255));
        lblWELCOME1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWELCOME1.setText("Вход");

        lblMinimise.setFont(new java.awt.Font("Apple Braille", 2, 24)); // NOI18N
        lblMinimise.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimise.setText("-");
        lblMinimise.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimiseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginpnlLayout = new javax.swing.GroupLayout(loginpnl);
        loginpnl.setLayout(loginpnlLayout);
        loginpnlLayout.setHorizontalGroup(
            loginpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpnlLayout.createSequentialGroup()
                .addComponent(lblWELCOME1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimise, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        loginpnlLayout.setVerticalGroup(
            loginpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWELCOME1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinimise, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainpnlLayout = new javax.swing.GroupLayout(mainpnl);
        mainpnl.setLayout(mainpnlLayout);
        mainpnlLayout.setHorizontalGroup(
            mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainpnlLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUSERNAME)
                    .addComponent(lblPASSWORD))
                .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainpnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswrdfldlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfldUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpnlLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnREGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        mainpnlLayout.setVerticalGroup(
            mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpnlLayout.createSequentialGroup()
                .addComponent(loginpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(notlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfldUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUSERNAME))
                .addGap(38, 38, 38)
                .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pswrdfldlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPASSWORD))
                .addGap(18, 18, 18)
                .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnREGISTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGINActionPerformed
        User obj;
       
          
        obj=new User(txtfldUSERNAME.getText(),pswrdfldlogin.getText());
       
        FileWorker obj1=new FileWorker();
        
        try {
            System.out.println(obj1.checkIfexistingLogin(obj));
            if(obj1.checkIfexistingLogin(obj)==true){
                
                dispose();
                new StartGamePanel().setVisible(true);
                
            }
            else{
                notlbl.setVisible(true);
                
                
            }
        } catch (IOException ex) {
            System.out.println("Error");
        }
        
          
        
    }//GEN-LAST:event_btnLOGINActionPerformed

    private void btnREGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREGISTERActionPerformed
        // TODO add your handling code here:
        dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_btnREGISTERActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked

        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimiseMouseClicked
        
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimiseMouseClicked

    public static void Run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLOGIN;
    private javax.swing.JButton btnREGISTER;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimise;
    private javax.swing.JLabel lblPASSWORD;
    private javax.swing.JLabel lblUSERNAME;
    private javax.swing.JLabel lblWELCOME1;
    private javax.swing.JPanel loginpnl;
    private javax.swing.JPanel mainpnl;
    private javax.swing.JLabel notlbl;
    private javax.swing.JPasswordField pswrdfldlogin;
    private javax.swing.JTextField txtfldUSERNAME;
    // End of variables declaration//GEN-END:variables
}
