/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stanibogat1;

import java.util.Random;

/**
 *
 * @author user
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }
    private LinkedList<Questions> list1;
    private LinkedList<Questions> list2;
    private LinkedList<Questions> list3;
    
    private Questions randQuestion(int difficulty) 
    {
        list1=new LinkedList<>();
        Random rand = new Random();
        if (difficulty == 1) 
        {
            int k = rand.nextInt(list1.size());
            Questions qu;
            qu = list1.get(k);
            list1.remove(k);
            return qu;
        } 
        else if (difficulty == 2) 
        {
            int k = rand.nextInt(list2.size());
            Questions qu;
            qu = list2.get(k);
            list2.remove(k);
            return qu;
        } 
        else 
        {   
            int k = rand.nextInt(list3.size());
            Questions qu;
            qu = list3.get(k);
            list3.remove(k);
            return qu;
        }
    }
    
    

    private Stack fillStack(Stack<Questions> stack)
    {
        if(stack.size()==15)
        {
            return stack;
        }
        else if(stack.size()<5)
        {
            stack.push(randQuestion(1));
            return fillStack(stack);
        }
        else if(stack.size()>5 && stack.size()<10)
        {
            stack.push(randQuestion(2));
            return fillStack(stack);
        }
        else 
        {
            stack.push(randQuestion(3));
             return fillStack(stack);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnpnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        mnpnl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 140, -1));

        jLabel3.setText("jLabel3");
        mnpnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 140, -1));

        jLabel4.setText("jLabel4");
        mnpnl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 140, -1));

        jLabel5.setText("jLabel5");
        mnpnl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 140, -1));

        jLabel6.setText("jLabel6");
        mnpnl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 340, 40));

        jLabel7.setText("jLabel7");
        mnpnl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MicrosoftTeams-image.png"))); // NOI18N
        mnpnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel mnpnl;
    // End of variables declaration//GEN-END:variables
}
